.TH MYCAT 1 "September 2025" "Version 1.0" "User Commands"
.SH Zaneeha
mycat \- concatenate and display files
.SH SYNOPSIS
.B mycat
[\fIFILE\fR]...
.SH DESCRIPTION
The
.B mycat
function reads each FILE in sequence and writes it to standard output.
If no FILE is specified, standard input is read.
.SH AUTHOR
Your Name <zaneehaafzal@gmail.com>
